spring:
  profiles:
    active: @spring.profiles.active@

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      show-sql: true
  servlet.multipart.max-file-size: 50MB

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:mysql://fpsz-db-server.c93ujvlm4zo7.ap-south-1.rds.amazonaws.com:3306/bethel
    username: root
    password: root1234
    pool-size: 30

application:
   jwt:
      secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
      tokenPrefix: Bearer
      tokenExpirationAfterDays: 10




