spring.servlet.multipart.max-file-size=50MB

spring.datasource.url = jdbc:mysql://localhost:3306/bethel
spring.datasource.username = root
spring.datasource.password = passes

spring.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true


security.oauth2.client.registration.google.client-id = 442750471682-uiigu2qidm4ki127mgb8ae2bhsckpelo.apps.googleusercontent.com
security.oauth2.client.registration.google.client-secret = thoxftnpIcZPx2Sx7dY8R9L2
security.oauth2.client.registration.google.scope = email,profile

security:
  oauth2:
    client:
    registration:
    google:
    client-id: 442750471682-uiigu2qidm4ki127mgb8ae2bhsckpelo.apps.googleusercontent.com
    client-secret: thoxftnpIcZPx2Sx7dY8R9L2
        scope:
        - email
        - profile

application.jwt.secretKey=securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
application.jwt.tokenPrefix=Bearer 
application.jwt.tokenExpirationAfterDays=10




